#82
yurijmikhalevich/rclip pull request #141
Opened 2024-10-03 11:20 UTC by TheChaoticor

solved,connected with xnview

2024-10-03 11:21 UTC, TheChaoticor commented
Please review it

2024-10-05 11:46 UTC, yurijmikhalevich commented on rclip/main.py
> +  XNVIEW_PATH = "C:\\Program Files\\XnViewMP\\xnviewmp.exe"
1. What if I have xnview installed to a different path?
2. What if I don't have xnview installed?

2024-10-05 11:46 UTC, yurijmikhalevich commented on rclip/main.py
> +        if os.path.exists(XNVIEW_PATH):
Why does this always try to open the xnview?

1. What if I am on Linux/macOS?
2. What if I don't want to open xnview?

2024-10-05 11:47 UTC, yurijmikhalevich commented on rclip/main.py
> +  XNVIEW_PATH = "C:\\Program Files\\XnViewMP\\xnviewmp.exe"
3. Why xnview? What about other image viewers.

2024-10-05 11:52 UTC, yurijmikhalevich requested changes
Thank you for the initiative 🙌 

But the design of this PR is bad:
1. We probably shouldn't require the user to have xnview installed to use previews on Windows.
2. We shouldn't hardcode the path to xnview.
3. We shouldn't open result images in xnview by default.

A better version of this PR could be:
- no changes to rclip code
- a change to README.md showing how to use xnview together with rclip to view files

Another option may involve building a generic adapter/helper that may try calling an image viewer if the user passed a CLI arg to ask for this, but this is more involved, and I am not sure if we need to do it now. But happy to discuss different approach ideas.

Can you change this PR to:
- remove changes to the rclip code
- add an example on how to use rclip with xnview, similar to this one: https://github.com/yurijmikhalevich/rclip/blob/01801ea4d027804ab945ebf56902954544e7b3a8/README.md?plain=1#L121-L137

Thank you, and let me know if you have any questions 😄

2024-10-05 12:01 UTC, TheChaoticor commented
Thank you for your review.I was inspired by the issue and suggestion on xnview and i misunderstood thinking that the pr can be made successful by just connecting with xnview .I will improve my pr and let you know

2024-11-03 11:37 UTC, yurijmikhalevich commented
Closing as the PR is stale and broken.

2024-11-03 11:37 UTC, closed without merging